# Builds Update-Voicemeeter.bat (the double-click version) from Update-Voicemeeter.ps1.
# Run it after every change to the .ps1:   powershell -ExecutionPolicy Bypass -File tools\Build-Bat.ps1
#
# The .bat is a small launcher followed by the whole PowerShell script. When double-clicked, it copies
# the script (everything below the marker line) to %TEMP%\VoicemeeterUpdater and runs it from there.

$root = Split-Path $PSScriptRoot
$ps1  = [IO.File]::ReadAllText((Join-Path $root 'Update-Voicemeeter.ps1'))
$ps1  = ($ps1 -replace "`r`n", "`n") -replace "`n", "`r`n"

$head = @'
@echo off
rem ======================================================================
rem  Voicemeeter Updater - just double-click this file.
rem  https://github.com/Taimauurufu/Voicemeeter-Updater
rem
rem  This file contains a PowerShell script (below the "#PS1-BELOW" line).
rem  It is copied to %TEMP%\VoicemeeterUpdater and run from there.
rem  Generated by tools\Build-Bat.ps1 - edit Update-Voicemeeter.ps1 instead.
rem ======================================================================
setlocal
title Voicemeeter Updater
set "VMU_SELF=%~f0"
set "VMU_DIR=%TEMP%\VoicemeeterUpdater"
set "VMU_PS1=%TEMP%\VoicemeeterUpdater\Update-Voicemeeter.ps1"
if not exist "%VMU_DIR%" mkdir "%VMU_DIR%"
powershell -NoProfile -ExecutionPolicy Bypass -Command "$t = [IO.File]::ReadAllText($env:VMU_SELF); $i = $t.IndexOf([char]10 + '#' + 'PS1-BELOW'); if ($i -lt 0) { exit 1 }; $i = $t.IndexOf([char]10, $i + 1) + 1; [IO.File]::WriteAllText($env:VMU_PS1, $t.Substring($i)); exit 0"
if errorlevel 1 (
    echo Could not extract the PowerShell script from this file.
    pause
    exit /b 1
)
powershell -NoProfile -ExecutionPolicy Bypass -File "%VMU_PS1%" %*
exit /b
#PS1-BELOW
'@
$head = ($head -replace "`r`n", "`n") -replace "`n", "`r`n"

$out = Join-Path $root 'Update-Voicemeeter.bat'
[IO.File]::WriteAllText($out, $head + "`r`n" + $ps1, (New-Object Text.UTF8Encoding($false)))
"Built $out"
